# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-03-16 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfogestiShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpa', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=2, null=True)),
                ('activo', models.NullBooleanField()),
            ],
            options={
                'db_table': '"INFOGESTI"."CLIENTE_EMBARCACION"',
                'managed': False,
            },
        ),
    ]
