# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-03-16 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_infogestishipment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='infogestishipment',
            table='INFOGESTI"."CLIENTE_EMBARCACION',
        ),
    ]
