# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210608_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='base_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='captaincy_province',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='owner_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='province_number',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='registry_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
