# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-11 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210611_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artemisa',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='camaguey',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='ciegodeavila',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='cienfuegos',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='granma',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='guantanamo',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='holguin',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='isladelajuventud',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='lahabana',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='lastunas',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='matanzas',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='mayabeque',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='pinardelrio',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='santiagodecuba',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='santicespiritud',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='dpa',
        ),
        migrations.RemoveField(
            model_name='villaclara',
            name='dpa',
        ),
    ]
