# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-03-16 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210316_1006'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='infogestishipment',
            table='"INFOGESTI"."C_CLIENTE_EMBARCACION"',
        ),
    ]
