# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-14 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210611_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaHabana',
        ),
    ]
