# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-14 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_lahabana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
