# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaHabana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(blank=True, max_length=400, null=True)),
                ('estadovehiculo', models.CharField(blank=True, max_length=400, null=True)),
                ('marcavehiculo', models.CharField(blank=True, max_length=400, null=True)),
                ('chapanueva', models.CharField(blank=True, max_length=400, null=True)),
                ('numeromotor', models.CharField(blank=True, max_length=400, null=True)),
                ('numerocarroseria', models.CharField(blank=True, max_length=400, null=True)),
                ('marcamotor', models.CharField(blank=True, max_length=400, null=True)),
                ('numeroidentidad', models.CharField(blank=True, max_length=400, null=True)),
                ('datospersona', models.CharField(blank=True, max_length=400, null=True)),
                ('direccion', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(blank=True, max_length=400, null=True)),
                ('estadovehiculo', models.CharField(blank=True, max_length=400, null=True)),
                ('marcavehiculo', models.CharField(blank=True, max_length=400, null=True)),
                ('chapanueva', models.CharField(blank=True, max_length=400, null=True)),
                ('numeromotor', models.CharField(blank=True, max_length=400, null=True)),
                ('numerocarroseria', models.CharField(blank=True, max_length=400, null=True)),
                ('marcamotor', models.CharField(blank=True, max_length=400, null=True)),
                ('numeroidentidad', models.CharField(blank=True, max_length=400, null=True)),
                ('datospersona', models.CharField(blank=True, max_length=400, null=True)),
                ('direccion', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
