# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-03-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210316_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"INFOGESTI"."CLIENTE"',
                'managed': False,
            },
        ),
    ]
