# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-04-01 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210323_1711'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='"INFOGESTI"."CLIENTE"',
        ),
    ]
